version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  account-service:
    build:
      context: ./account-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  notification-service:
    build:
      context: ./notification-service
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '15672:15672'
      - '5672:5672'
    restart: unless-stopped